# Generated by Django 4.2.2 on 2023-08-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DemandeChauffeur', '0003_remove_reserver_chauffeur'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chauffeur',
            name='reserver',
            field=models.ManyToManyField(blank=True, to='DemandeChauffeur.reserver'),
        ),
    ]
