# Generated by Django 4.2.2 on 2023-08-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DemandeChauffeur', '0004_reserver_chauffeur'),
        ('users', '0002_chauffeur_reserver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chauffeur',
            name='reserver',
            field=models.ManyToManyField(blank=True, related_name='Reserver', to='DemandeChauffeur.reserver'),
        ),
    ]
