# Generated by Django 4.2.2 on 2023-08-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeChauffeur',
            fields=[
                ('demande_id', models.AutoField(primary_key=True, serialize=False)),
                ('reserve', models.BooleanField(default=False)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('date_deplacement', models.DateField()),
                ('admin_approuver', models.BooleanField(default=False)),
                ('lieu_deplacement', models.CharField(blank=True, max_length=500)),
                ('coordonees', models.CharField(blank=True, max_length=200)),
                ('mission', models.CharField(blank=True, max_length=200)),
                ('duree', models.CharField(blank=True, max_length=50)),
                ('last_modified', models.DateField()),
                ('status', models.CharField(choices=[('Nouvelle Demande', 'Nouvelle Demande'), ('Confirmer par admin', 'Confirmer par admin'), ('Demande annuler', 'Demande annuler')], default='Nouvelle Demande', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reserver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reserver', models.DateField()),
            ],
        ),
    ]
