# Generated by Django 4.2.2 on 2023-08-17 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('DemandeChauffeur', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reserver',
            name='chauffeur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.chauffeur'),
        ),
        migrations.AddField(
            model_name='demandechauffeur',
            name='chauffeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.chauffeur'),
        ),
        migrations.AddField(
            model_name='demandechauffeur',
            name='demandeur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
