# Generated by Django 4.2.2 on 2023-08-17 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DemandeChauffeur', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserver',
            name='chauffeur',
        ),
    ]
