# Generated by Django 4.2.2 on 2023-08-17 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_chauffeur_reserver'),
        ('DemandeChauffeur', '0003_remove_reserver_chauffeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserver',
            name='chauffeur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Chauffeur', to='users.chauffeur'),
        ),
    ]
