# Generated by Django 4.2.2 on 2023-08-22 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DemandeChauffeur', '0004_reserver_chauffeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserver',
            name='demande',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DemandeChauffeur', to='DemandeChauffeur.demandechauffeur'),
        ),
    ]
