# Generated by Django 4.2.2 on 2023-08-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DemandeChauffeur', '0006_demandechauffeur_duree_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandechauffeur',
            name='date_deplacement',
            field=models.DateTimeField(),
        ),
    ]
