# Generated by Django 4.2.2 on 2023-08-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DemandeChauffeur', '0007_alter_demandechauffeur_date_deplacement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserver',
            name='date_reserver',
            field=models.DateTimeField(),
        ),
    ]
