# Generated by Django 4.2.2 on 2023-08-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DemandeChauffeur', '0009_demandechauffeur_date_retour_reserver_date_retour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandechauffeur',
            name='status',
            field=models.CharField(choices=[('Nouvelle Demande', 'Nouvelle Demande'), ('Confirmer par admin', 'Confirmer par admin'), ('Demande annuler', 'Demande annuler'), ('Choisissez nouvelle dates', 'Choisissez nouvelle dates')], default='Nouvelle Demande', max_length=50),
        ),
    ]
