# Generated by Django 4.2.2 on 2023-08-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DemandeChauffeur', '0010_alter_demandechauffeur_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandechauffeur',
            name='manager_valider',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='demandechauffeur',
            name='status',
            field=models.CharField(choices=[('Nouvelle Demande', 'Nouvelle Demande'), ('Confirmer par admin', 'Confirmer par admin'), ('Confirmer par Superieur', 'Confirmer par Superieur'), ('Demande annuler', 'Demande annuler'), ('Choisissez nouvelle dates', 'Choisissez nouvelle dates')], default='Nouvelle Demande', max_length=50),
        ),
    ]
