# Generated by Django 4.2.2 on 2023-08-17 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DemandeMateriel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='demandemodel',
            name='demandeur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bonlivraison',
            name='demande',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DemandeMateriel.demandemodel'),
        ),
    ]
